from __future__ import annotations

from typing import Any

from iltero_schemas.ast import parse_document, source_digest
from iltero_schemas.canonical import digest
from iltero_schemas.compiler import COMPILER_VERSION, RUNTIME, RegoModule, compile, package_of

RESOURCE = {"kind": "resource", "provider": "aws", "resource_types": ["aws_db_instance"]}


def _source(assert_: Any, when: Any = None, assertion_id: str = "ACME.TEST.CASE") -> dict[str, Any]:
    spec: dict[str, Any] = {"stage": "plan", "target": RESOURCE, "assert": assert_}
    if when is not None:
        spec["when"] = when
    return {
        "apiVersion": "iltero.io/v1",
        "kind": "TechnicalAssertion",
        "metadata": {"id": assertion_id, "version": "2.1.0", "title": "t"},
        "spec": spec,
    }


def _module(assert_: Any, when: Any = None, assertion_id: str = "ACME.TEST.CASE") -> RegoModule:
    return compile(parse_document(_source(assert_, when, assertion_id)))


def _rules(module: RegoModule) -> str:
    return module.source.decode("utf-8").split("\n# Runtime shared", 1)[0]


def test_package_and_entrypoint_are_one_key_under_the_prefix() -> None:
    module = _module({"path": "resource.x", "equal": 1}, assertion_id="ACME.AWS.RDS.ENCRYPTED")
    assert package_of("ACME.AWS.RDS.ENCRYPTED") == 'iltero.assertions["ACME.AWS.RDS.ENCRYPTED"]'
    assert module.assertion_id == "ACME.AWS.RDS.ENCRYPTED"
    assert module.package == 'iltero.assertions["ACME.AWS.RDS.ENCRYPTED"]'
    assert module.entrypoint == 'data.iltero.assertions["ACME.AWS.RDS.ENCRYPTED"].evaluate'
    assert 'package iltero.assertions["ACME.AWS.RDS.ENCRYPTED"]\n' in _rules(module)


def test_module_is_self_describing_and_carries_the_runtime_verbatim() -> None:
    document = _source({"path": "resource.x", "equal": 1})
    module = compile(parse_document(document))
    rules = _rules(module)
    assert rules.startswith(f"# Generated by the iltero-schemas assertion compiler {COMPILER_VERSION}.")
    assert 'assertion_id := "ACME.TEST.CASE"\n' in rules
    assert 'assertion_version := "2.1.0"\n' in rules
    assert "ast_version := 1\n" in rules
    assert f'assertion_source_digest := "{source_digest(parse_document(document))}"\n' in rules
    assert module.source.decode("utf-8").endswith(RUNTIME)
    assert module.digest == digest(module.source)


def test_compilation_is_deterministic() -> None:
    check = {
        "all": [
            {"path": "resource.x", "equal": 1},
            {"exists": {"in": "resource.r", "where": {"path": "item.a", "equal": 2}}},
        ]
    }
    assert _module(check) == _module(check)


def test_absent_when_is_a_constant_true_guard() -> None:
    rules = _rules(_module({"path": "resource.x", "equal": 1}))
    assert "_has_when := false\n" in rules
    assert "_guard := _true\n" in rules
    rules = _rules(
        _module({"path": "resource.x", "equal": 1}, when={"path": "context.environment.name", "equal": "production"})
    )
    assert "_has_when := true\n" in rules
    assert '_guard := predicate("equal", lookup("context.environment.name"), literal("production"))\n' in rules


def test_literal_and_reference_operands() -> None:
    rules = _rules(_module({"path": "resource.x", "equal": {"path": "plan.digest"}}))
    assert '_check := predicate("equal", lookup("resource.x"), lookup("plan.digest"))\n' in rules
    rules = _rules(_module({"path": "resource.x", "in": ["a", "b"]}))
    assert 'predicate("in", lookup("resource.x"), literal(["a", "b"]))' in rules


def test_combinators_render_as_runtime_calls() -> None:
    rules = _rules(_module({"any": [{"not": {"path": "resource.x", "equal": 1}}, {"path": "resource.y", "equal": 2}]}))
    assert "_check := any_of([\n\tnot_of(predicate(" in rules
    assert "\n])\n" in rules


def test_exists_becomes_a_numbered_where_function_and_item_lookups() -> None:
    rules = _rules(
        _module(
            {
                "exists": {
                    "in": "resource.related",
                    "where": {"exists": {"in": "item.rules", "where": {"path": "item.port", "equal": 443}}},
                }
            }
        )
    )
    outer = 'lookup("resource.related")'
    inner = 'lookup_item(item, "item.rules")'
    assert f"_check := exists_of({outer}, [where_1(e1) | some e1 in elements({outer})])" in rules
    assert f"where_1(item) := exists_of({inner}, [where_2(e2) | some e2 in elements({inner})])" in rules
    assert 'where_2(item) := predicate("equal", lookup_item(item, "item.port"), literal(443))' in rules


def test_exists_without_where_counts_elements() -> None:
    rules = _rules(_module({"exists": {"in": "resource.related"}}))
    assert (
        '_check := exists_of(lookup("resource.related"), [_true | some _ in elements(lookup("resource.related"))])'
        in rules
    )


def test_non_ascii_literals_are_kept_as_utf8() -> None:
    module = _module({"path": "resource.x", "equal": "café"})
    assert 'literal("café")' in module.source.decode("utf-8")
