"""Compile an assertion AST to a Rego module.

``compile`` is a pure function of the AST and ``COMPILER_VERSION``: the same
assertion always yields the same bytes, which is what lets a consumer
recompile an assertion and compare the result to the module it was handed.
The generated module is self-contained — the assertion's own rules followed
by a verbatim copy of ``runtime.rego`` — and exposes
``data.iltero.assertions["<id>"].evaluate``, which returns one result
``{subject, status, reason, observations}`` for the subject the input
describes. ``status`` is ``pass``, ``fail``, ``unknown`` or ``not_applicable``.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from importlib import resources
from typing import Any

from iltero_schemas.ast.nodes import (
    AST_VERSION,
    All,
    AnyOf,
    Assertion,
    Exists,
    Expr,
    Literal,
    Not,
    Path,
    Predicate,
    to_json,
)
from iltero_schemas.ast.roots import ITEM_ROOT
from iltero_schemas.canonical import digest, digest_of

# Bumped whenever the generated bytes for any AST change.
COMPILER_VERSION = "1.0.0"
# Every assertion is one key under this package, so no assertion's package
# can sit inside another's.
PACKAGE_PREFIX = "iltero.assertions"
ENTRYPOINT_RULE = "evaluate"

RUNTIME: str = resources.files("iltero_schemas.compiler").joinpath("runtime.rego").read_text(encoding="utf-8")

_HEADER = (
    "# Generated by the iltero-schemas assertion compiler {version}. Do not edit:\n"
    "# a consumer recompiles the assertion and refuses a module that differs.\n"
)


@dataclass(frozen=True)
class RegoModule:
    """One compiled assertion: its package, the rule to query, and the bytes to load."""

    assertion_id: str
    package: str
    entrypoint: str
    source: bytes
    digest: str


def package_of(assertion_id: str) -> str:
    """The Rego package of an assertion: ``iltero.assertions["<id>"]``."""
    return f"{PACKAGE_PREFIX}[{_rego(assertion_id)}]"


def _rego(value: Any) -> str:
    """A JSON value as a Rego literal, spaced the way ``opa fmt`` writes it."""
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(", ", ": "))


def _lookup(path: Path) -> str:
    if path.root == ITEM_ROOT:
        return f"lookup_item(item, {_rego(path.dotted())})"
    return f"lookup({_rego(path.dotted())})"


class _Emitter:
    def __init__(self) -> None:
        self.functions: list[str] = []
        self.counter = 0

    def expr(self, expr: Expr, depth: int) -> str:
        if isinstance(expr, Predicate):
            return self.predicate(expr)
        if isinstance(expr, (All, AnyOf)):
            name = "all_of" if isinstance(expr, All) else "any_of"
            return f"{name}({self.list([self.expr(arg, depth + 1) for arg in expr.args], depth)})"
        if isinstance(expr, Not):
            return f"not_of({self.expr(expr.arg, depth)})"
        return self.exists(expr)

    def predicate(self, expr: Predicate) -> str:
        if isinstance(expr.operand, Literal):
            value = expr.operand.value
            operand = f"literal({_rego(list(value) if isinstance(value, tuple) else value)})"
        else:
            operand = _lookup(expr.operand)
        return f"predicate({_rego(expr.op.value)}, {_lookup(expr.path)}, {operand})"

    def exists(self, expr: Exists) -> str:
        collection = _lookup(expr.collection)
        if expr.where is None:
            return f"exists_of({collection}, [_true | some _ in elements({collection})])"
        self.counter += 1
        number = self.counter
        # The function is emitted after its body is compiled, so nested
        # `exists` functions come first; numbering keeps names stable.
        body = self.expr(expr.where, 0)
        self.functions.append(f"where_{number}(item) := {body}\n")
        return f"exists_of({collection}, [where_{number}(e{number}) | some e{number} in elements({collection})])"

    @staticmethod
    def list(items: list[str], depth: int) -> str:
        if len(items) == 1:
            return f"[{items[0]}]"
        inner = "\t" * (depth + 1)
        outer = "\t" * depth
        return "[\n" + "".join(f"{inner}{item},\n" for item in items) + f"{outer}]"


def compile(assertion: Assertion) -> RegoModule:
    """Compile ``assertion`` to its Rego module."""
    package = package_of(assertion.id)
    emitter = _Emitter()
    guard = "_true" if assertion.when is None else emitter.expr(assertion.when, 0)
    check = emitter.expr(assertion.assert_, 0)
    rules = [
        f"package {package}\n",
        f"assertion_id := {_rego(assertion.id)}\n",
        f"assertion_version := {_rego(assertion.version)}\n",
        f"ast_version := {AST_VERSION}\n",
        f"assertion_source_digest := {_rego(digest_of(to_json(assertion)))}\n",
        f"_has_when := {_rego(assertion.when is not None)}\n",
        f"_guard := {guard}\n",
        f"_check := {check}\n",
        *emitter.functions,
    ]
    source = _HEADER.format(version=COMPILER_VERSION) + "\n".join(rules) + "\n" + RUNTIME
    encoded = source.encode("utf-8")
    return RegoModule(
        assertion_id=assertion.id,
        package=package,
        entrypoint=f"data.{package}.{ENTRYPOINT_RULE}",
        source=encoded,
        digest=digest(encoded),
    )
