# Generated by the iltero-schemas assertion compiler 1.0.0. Do not edit:
# a consumer recompiles the assertion and refuses a module that differs.
package iltero.assertions["VEC.LITERALS.EDGE"]

assertion_id := "VEC.LITERALS.EDGE"

assertion_version := "1.0.0"

ast_version := 1

assertion_source_digest := "sha256:06f76acad2b3604b50ea706b8eb2d80a2f817a2cf4b8bc0aa82888a05fd2e12a"

_has_when := false

_guard := _true

_check := all_of([
	predicate("equal", lookup("resource.after.s128"), literal("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")),
	predicate("equal", lookup("resource.after.s129"), literal("bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")),
	predicate("contains", lookup("resource.after.l4"), literal(4)),
])

# Runtime shared by every compiled assertion. It is copied verbatim into each
# generated module after the assertion's own rules, so a module is complete
# on its own. Evaluation is three-valued: every expression yields a result
# {"status": "true" | "false" | "unknown", "predicates": [...]} and, when the
# status is "unknown", an "unknown" entry {"path", "reason"} naming the first
# operand that could not be resolved.

# A value no evaluation input can contain, used to tell "absent" from "null".
_missing := {"__iltero_missing": true}

# A marker's reason is copied into evidence only when it is a short
# lower-case token; anything else is reported as "unspecified".
_reason_token_max := 64

_reason_chars := {c | some c in split("abcdefghijklmnopqrstuvwxyz0123456789_", "")}

_reason_token(value) if {
	is_string(value)
	count(value) > 0
	count(value) <= _reason_token_max
	substring(value, 0, 1) != "_"
	not startswith(value, "0")
	every c in split(value, "") {
		c in _reason_chars
	}
}

# The two non-value nodes an input may carry, and the reason each yields.
_sentinel_reason(node) := "redacted" if {
	is_object(node)
	node.__redacted == true
} else := node.reason if {
	is_object(node)
	node.__unknown == true
	_reason_token(node.reason)
} else := "unspecified" if {
	is_object(node)
	node.__unknown == true
}

_unknown_value(name, reason) := {"known": false, "path": name, "reason": reason}

# Resolve the names in `segments` under `root`: known with its value, or
# unknown with the reason of the first sentinel met, or path_missing.
_resolve(root, name, segments) := _unknown_value(name, reason) if {
	reason := _sentinel_reason(root)
} else := {"known": true, "path": name, "value": root} if {
	count(segments) == 0
} else := _unknown_value(name, "path_missing") if {
	not is_object(root)
} else := _unknown_value(name, reason) if {
	hits := [i |
		some i in numbers.range(0, count(segments) - 1)
		_sentinel_reason(object.get(root, array.slice(segments, 0, i + 1), _missing))
	]
	count(hits) > 0
	reason := _sentinel_reason(object.get(root, array.slice(segments, 0, hits[0] + 1), _missing))
} else := _unknown_value(name, "path_missing") if {
	object.get(root, segments, _missing) == _missing
} else := {"known": true, "path": name, "value": object.get(root, segments, _missing)}

# A dotted path from the input root.
lookup(name) := _resolve(input, name, split(name, "."))

# A dotted path from the current collection element, written `item.<...>`.
lookup_item(item, name) := _resolve(item, name, array.slice(split(name, "."), 1, count(split(name, "."))))

# A constant operand, already known.
literal(value) := {"known": true, "value": value}

# The result of an absent `when` guard, and of a `where` clause that is absent.
_true := {"status": "true", "predicates": []}

_comparable(left, right) if {
	is_number(left)
	is_number(right)
}

_comparable(left, right) if {
	is_string(left)
	is_string(right)
}

_member(left, right) if {
	is_array(right)
	left in right
}

# Every operator is total over known values. A subject value of the wrong
# type does not satisfy `equal`, an ordering, `in` or `contains`, so those
# are false; `not_equal` and `not_in` are their exact negations. A reference
# or collection of the wrong shape is a producer defect and is reported as
# unknown before any operator runs (see `predicate` and `exists_of`).
compare("equal", left, right) := left == right

compare("not_equal", left, right) := left != right

compare("greater_than", left, right) if {
	_comparable(left, right)
	left > right
} else := false

compare("greater_than_or_equal", left, right) if {
	_comparable(left, right)
	left >= right
} else := false

compare("less_than", left, right) if {
	_comparable(left, right)
	left < right
} else := false

compare("less_than_or_equal", left, right) if {
	_comparable(left, right)
	left <= right
} else := false

compare("in", left, right) if {
	_member(left, right)
} else := false

compare("not_in", left, right) if {
	not _member(left, right)
} else := false

compare("contains", left, right) if {
	is_array(left)
	right in left
} else := false

_status(true) := "true"

_status(false) := "false"

# What an observation records of a value: short scalars and short lists of
# them as they are, everything else by shape, never by content.
_short(value) if {
	is_string(value)
	count(value) <= 128
}

_short(value) if {
	is_number(value)
}

_short(value) if {
	is_boolean(value)
}

_short(value) if {
	is_null(value)
}

_summary(value) := value if {
	_short(value)
} else := value if {
	is_array(value)
	count(value) <= 4
	every element in value {
		_short(element)
	}
} else := {"type": "string", "length": count(value)} if {
	is_string(value)
} else := {"type": "array", "count": count(value)} if {
	is_array(value)
} else := {"type": "object"} if {
	is_object(value)
} else := {"type": "set"}

# A reference operand for `in` / `not_in` must resolve to a list.
_list_operators := {"in", "not_in"}

_shape_unknown(op, right) := {"path": right.path, "reason": "not_a_list"} if {
	op in _list_operators
	right.known
	right.path
	not is_array(right.value)
}

_first_unknown(operands) := {"path": u.path, "reason": u.reason} if {
	unknowns := [o | some o in operands; not o.known]
	u := unknowns[0]
}

# What the observation records of the operand: a reference by path and its
# resolved value, a literal by value.
_expected(right) := {"expected": {"ref": right.path}, "resolved": resolved} if {
	right.path
	resolved := _summary(right.value)
} else := {"expected": {"ref": right.path}, "resolved": null} if {
	right.path
} else := {"expected": _summary(right.value)}

_observation(op, left, right, actual, status) := object.union(
	{"path": left.path, "op": op, "actual": actual, "status": status},
	_expected(right),
)

predicate(op, left, right) := {"status": "unknown", "unknown": unknown, "predicates": [obs]} if {
	unknown := _first_unknown([left, right])
	obs := _observation(op, left, right, null, "unknown")
} else := {"status": "unknown", "unknown": unknown, "predicates": [obs]} if {
	unknown := _shape_unknown(op, right)
	obs := _observation(op, left, right, _summary(left.value), "unknown")
} else := {"status": status, "predicates": [obs]} if {
	status := _status(compare(op, left.value, right.value))
	obs := _observation(op, left, right, _summary(left.value), status)
}

_predicates(results) := [p | some r in results; some p in r.predicates]

_first_unknown_result(results) := unknowns[0] if {
	unknowns := [r.unknown | some r in results; r.status == "unknown"]
}

all_of(results) := {"status": "false", "predicates": _predicates(results)} if {
	some r in results
	r.status == "false"
} else := {"status": "unknown", "unknown": unknown, "predicates": _predicates(results)} if {
	unknown := _first_unknown_result(results)
} else := {"status": "true", "predicates": _predicates(results)}

any_of(results) := {"status": "true", "predicates": _predicates(results)} if {
	some r in results
	r.status == "true"
} else := {"status": "unknown", "unknown": unknown, "predicates": _predicates(results)} if {
	unknown := _first_unknown_result(results)
} else := {"status": "false", "predicates": _predicates(results)}

not_of(result) := {"status": "false", "predicates": result.predicates} if {
	result.status == "true"
} else := {"status": "true", "predicates": result.predicates} if {
	result.status == "false"
} else := result

# The elements of a collection lookup, or none when it is unknown or not a list.
# (A set never occurs in JSON input; the branch above keeps `_summary` total.)
elements(collection) := collection.value if {
	collection.known
	is_array(collection.value)
} else := []

_exists_obs(collection, status, matched) := {
	"path": collection.path,
	"op": "exists",
	"expected": null,
	"actual": actual,
	"status": status,
	"matched": matched,
} if {
	collection.known
	actual := _summary(collection.value)
} else := {"path": collection.path, "op": "exists", "expected": null, "actual": null, "status": status, "matched": matched}

exists_of(collection, results) := {"status": "unknown", "unknown": unknown, "predicates": [obs]} if {
	not collection.known
	unknown := {"path": collection.path, "reason": collection.reason}
	obs := _exists_obs(collection, "unknown", null)
} else := {"status": "unknown", "unknown": unknown, "predicates": [obs]} if {
	not is_array(collection.value)
	unknown := {"path": collection.path, "reason": "not_a_list"}
	obs := _exists_obs(collection, "unknown", null)
} else := {"status": "true", "predicates": [obs]} if {
	matched := count([r | some r in results; r.status == "true"])
	matched > 0
	obs := _exists_obs(collection, "true", matched)
} else := {"status": "unknown", "unknown": unknown, "predicates": [obs]} if {
	unknown := _first_unknown_result(results)
	obs := _exists_obs(collection, "unknown", 0)
} else := {"status": "false", "predicates": [obs]} if {
	obs := _exists_obs(collection, "false", 0)
}

# One result for the subject the input describes.
_status_of_check := "pass" if {
	_check.status == "true"
} else := "fail" if {
	_check.status == "false"
} else := "unknown"

status := "not_applicable" if {
	_guard.status == "false"
} else := "unknown" if {
	_guard.status == "unknown"
} else := _status_of_check

_unknown := object.get(_guard, "unknown", null) if {
	_guard.status == "unknown"
} else := object.get(_check, "unknown", null) if {
	_guard.status == "true"
	_check.status == "unknown"
} else := null

# Every predicate observation, tagged with the clause it belongs to and its
# position, so a reason can name one unambiguously.
_clause(result, clause) := [object.union(p, {"clause": clause}) | some p in result.predicates]

_observed := [object.union(p, {"index": i}) |
	some i, p in array.concat(_clause(_guard, "when"), _clause(_check, "assert"))
]

reason := "when: false" if {
	status == "not_applicable"
} else := sprintf("%s: %s", [_unknown.path, _unknown.reason]) if {
	status == "unknown"
} else := "assert: true" if {
	status == "pass"
} else := sprintf("assert: false; predicate %d is false: %s %s", [first.index, first.path, first.op]) if {
	failed := [p | some p in _observed; p.clause == "assert"; p.status == "false"]
	first := failed[0]
} else := "assert: false; a negated expression held"

_when_status := _guard.status if {
	_has_when
} else := null

observations := {
	"when": _when_status,
	"predicates": _observed,
	"unknown": _unknown,
}

# The subject is echoed as identity only, bounded like every observed value.
_subject := {"kind": _summary(object.get(subject, "kind", null)), "id": _summary(object.get(subject, "id", null))} if {
	is_object(input)
	subject := input.subject
	is_object(subject)
} else := null

evaluate := [{
	"subject": _subject,
	"status": status,
	"reason": reason,
	"observations": observations,
}]
